{ config, lib, pkgs, ... }:

# C:\Users\kylem\.psmux.conf — psmux, the native Windows tmux, rendered from
# the same palette and bindings as home/tmux.nix (see home/tmux-common.nix).
#
# A COPY, not a symlink: psmux is a Windows program and cannot follow a WSL
# symlink into /nix/store. Activation overwrites the file every switch, so edit
# it here, never on the Windows side.
#
# Plugins come from psmux's own manager (ppm) and its Windows ports, installed
# into C:\Users\kylem\.psmux\plugins by ppm itself (prefix+I), not by Nix.
# tmux-mode-indicator and tmux-suspend have no port: the indicator is rebuilt
# from format conditionals below, suspend is dropped (nested sessions only).
let
  cfg = config.kyle.psmux;
  common = import ./tmux-common.nix;
  inherit (common) catppuccin;
  target = "/mnt/c/Users/kylem/.psmux.conf";

  conf = pkgs.writeText "psmux.conf" ''
    # Generated by ~/nixosdotfiles/home/psmux.nix — edits here are overwritten.

    set -g default-terminal "tmux-256color"
    set -ga terminal-overrides ",xterm-256color*:Tc"
    set -g base-index 1
    setw -g pane-base-index 1
    set -g status-keys vi
    setw -g mode-keys vi
    set -g mouse on
    set -g history-limit 50000
    setw -g clock-mode-style 12

    unbind C-b
    set -g prefix C-space
    bind C-space send-prefix

    set -g @plugin 'psmux-plugins/ppm'
    set -g @plugin 'psmux-plugins/psmux-sensible'
    set -g @plugin 'psmux-plugins/psmux-resurrect'
    set -g @plugin 'psmux-plugins/psmux-continuum'
    set -g @resurrect-capture-pane-contents 'on'
    set -g @continuum-restore 'off'
    set -g @continuum-save-interval '1'

    ${common.bindingsAndAppearance}
    # Native stand-in for tmux-mode-indicator
    set -g status-right-length 100
    set -g status-right "#{?client_prefix,#[fg=${catppuccin.base} bg=${catppuccin.blue} bold] WAIT ,#{?pane_in_mode,#[fg=${catppuccin.base} bg=${catppuccin.yellow} bold] COPY ,#[fg=${catppuccin.base} bg=${catppuccin.green} bold] TMUX }}#[nobold]${common.statusRightTail} "

    # ppm must be initialized last
    run '~/.psmux/plugins/ppm/ppm.ps1'

    # psmux-sensible forces escape-time 50; re-apply ours after it
    set -s escape-time 1
  '';
in
{
  options.kyle.psmux.enable = lib.mkEnableOption ''
    C:\Users\kylem\.psmux.conf, copied out on every activation.

    Off by default and enabled per-host in home/wsl.nix, NOT in
    users/kyle/home.nix — artemis is the only NixOS host with a Windows side
  '';

  config = lib.mkIf cfg.enable {
    home.activation.psmuxConfig =
      lib.hm.dag.entryAfter [ "writeBoundary" ] ''
        if [ -d /mnt/c/Users/kylem ]; then
          $DRY_RUN_CMD install -m 644 ${conf} ${lib.escapeShellArg target}
        else
          echo "psmux: /mnt/c/Users/kylem is missing — ${target} not written" >&2
        fi
      '';
  };
}
